CREATE TABLE IF NOT EXISTS PRODUCT (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  MRP FLOAT,
  QUANTITY_IN_STOCK INTEGER,
  MANUFACTURER VARCHAR(255),
  CATEGORY_ID VARCHAR(255),
  IMAGE_ID VARCHAR(255),
  RESOURCE_ID VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USERS (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255),
  EMAIL VARCHAR(255),
  USERNAME VARCHAR(255),
  PASSWORD VARCHAR(255),
  ROLE VARCHAR(255),
  ACCOUNT_NON_EXPIRED BOOLEAN,
  ACCOUNT_NON_LOCKED BOOLEAN,
  CREDENTIALS_NON_EXPIRED BOOLEAN,
  ENABLED BOOLEAN,
  PRIMARY KEY (ID)
);